################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../RTD/src/Adc_Sar_Ip.c \
../RTD/src/Adc_Sar_Ip_Irq.c \
../RTD/src/CDD_I2c.c \
../RTD/src/CDD_Sbc_fs23.c \
../RTD/src/Clock_Ip.c \
../RTD/src/Clock_Ip_Data.c \
../RTD/src/Clock_Ip_Divider.c \
../RTD/src/Clock_Ip_DividerTrigger.c \
../RTD/src/Clock_Ip_ExtOsc.c \
../RTD/src/Clock_Ip_FracDiv.c \
../RTD/src/Clock_Ip_Frequency.c \
../RTD/src/Clock_Ip_Gate.c \
../RTD/src/Clock_Ip_IntOsc.c \
../RTD/src/Clock_Ip_Irq.c \
../RTD/src/Clock_Ip_Monitor.c \
../RTD/src/Clock_Ip_Pll.c \
../RTD/src/Clock_Ip_ProgFreqSwitch.c \
../RTD/src/Clock_Ip_Selector.c \
../RTD/src/Clock_Ip_Specific.c \
../RTD/src/Cmp_Ip.c \
../RTD/src/Dem.c \
../RTD/src/Dem_stub.c \
../RTD/src/Det.c \
../RTD/src/Det_stub.c \
../RTD/src/Dio.c \
../RTD/src/Dio_Ipw.c \
../RTD/src/Dma_Ip.c \
../RTD/src/Dma_Ip_Driver_State.c \
../RTD/src/Dma_Ip_Hw_Access.c \
../RTD/src/Dma_Ip_Irq.c \
../RTD/src/Dma_Ip_Multicore.c \
../RTD/src/Dspi_Ip.c \
../RTD/src/Dspi_Ip_Irq.c \
../RTD/src/Emios_Gpt_Ip.c \
../RTD/src/Emios_Icu_Ip.c \
../RTD/src/Emios_Icu_Ip_Irq.c \
../RTD/src/Flexio_I2c_Ip.c \
../RTD/src/Flexio_Spi_Ip.c \
../RTD/src/Flexio_Spi_Ip_Irq.c \
../RTD/src/Gpt.c \
../RTD/src/Gpt_Ipw.c \
../RTD/src/I2c_Ipw.c \
../RTD/src/Icu.c \
../RTD/src/Icu_Ipw.c \
../RTD/src/Igf_Port_Ip.c \
../RTD/src/IntCtrl_Ip.c \
../RTD/src/Lpi2c_Ip.c \
../RTD/src/Lpi2c_Ip_HwAccess.c \
../RTD/src/Lpi2c_Ip_Irq.c \
../RTD/src/Lpspi_Ip.c \
../RTD/src/Lpspi_Ip_Irq.c \
../RTD/src/Lpuart_Uart_Ip.c \
../RTD/src/Lpuart_Uart_Ip_Irq.c \
../RTD/src/Mcu.c \
../RTD/src/Mcu_Dem_Wrapper.c \
../RTD/src/Mcu_Ipw.c \
../RTD/src/Mpu_M7_Ip.c \
../RTD/src/OsIf_Interrupts.c \
../RTD/src/OsIf_Timer.c \
../RTD/src/OsIf_Timer_System.c \
../RTD/src/OsIf_Timer_System_Internal_Systick.c \
../RTD/src/Pit_Ip.c \
../RTD/src/Platform.c \
../RTD/src/Platform_Ipw.c \
../RTD/src/Port.c \
../RTD/src/Port_Ipw.c \
../RTD/src/Power_Ip.c \
../RTD/src/Power_Ip_AEC.c \
../RTD/src/Power_Ip_CortexM7.c \
../RTD/src/Power_Ip_DCM_GPR.c \
../RTD/src/Power_Ip_FLASH.c \
../RTD/src/Power_Ip_MC_ME.c \
../RTD/src/Power_Ip_MC_RGM.c \
../RTD/src/Power_Ip_MC_RGM_Irq.c \
../RTD/src/Power_Ip_PMC.c \
../RTD/src/Power_Ip_PMC_Irq.c \
../RTD/src/Power_Ip_Private.c \
../RTD/src/Ram_Ip.c \
../RTD/src/Rtc_Ip.c \
../RTD/src/SchM_Adc.c \
../RTD/src/SchM_Dio.c \
../RTD/src/SchM_Gpt.c \
../RTD/src/SchM_I2c.c \
../RTD/src/SchM_Icu.c \
../RTD/src/SchM_Mcl.c \
../RTD/src/SchM_Mcu.c \
../RTD/src/SchM_Platform.c \
../RTD/src/SchM_Port.c \
../RTD/src/SchM_Sbc_fs23.c \
../RTD/src/SchM_Spi.c \
../RTD/src/SchM_Uart.c \
../RTD/src/Siul2_Dio_Ip.c \
../RTD/src/Siul2_Icu_Ip.c \
../RTD/src/Siul2_Icu_Ip_Irq.c \
../RTD/src/Siul2_Port_Ip.c \
../RTD/src/Spi.c \
../RTD/src/Spi_Ipw.c \
../RTD/src/Stm_Ip.c \
../RTD/src/System_Ip.c \
../RTD/src/Tspc_Port_Ip.c \
../RTD/src/Wkpu_Ip.c \
../RTD/src/Wkpu_Ip_Irq.c \
../RTD/src/sbc_fs23_i2c_external_access.c \
../RTD/src/sbc_fs23_spi_external_access.c 

OBJS += \
./RTD/src/Adc_Sar_Ip.o \
./RTD/src/Adc_Sar_Ip_Irq.o \
./RTD/src/CDD_I2c.o \
./RTD/src/CDD_Sbc_fs23.o \
./RTD/src/Clock_Ip.o \
./RTD/src/Clock_Ip_Data.o \
./RTD/src/Clock_Ip_Divider.o \
./RTD/src/Clock_Ip_DividerTrigger.o \
./RTD/src/Clock_Ip_ExtOsc.o \
./RTD/src/Clock_Ip_FracDiv.o \
./RTD/src/Clock_Ip_Frequency.o \
./RTD/src/Clock_Ip_Gate.o \
./RTD/src/Clock_Ip_IntOsc.o \
./RTD/src/Clock_Ip_Irq.o \
./RTD/src/Clock_Ip_Monitor.o \
./RTD/src/Clock_Ip_Pll.o \
./RTD/src/Clock_Ip_ProgFreqSwitch.o \
./RTD/src/Clock_Ip_Selector.o \
./RTD/src/Clock_Ip_Specific.o \
./RTD/src/Cmp_Ip.o \
./RTD/src/Dem.o \
./RTD/src/Dem_stub.o \
./RTD/src/Det.o \
./RTD/src/Det_stub.o \
./RTD/src/Dio.o \
./RTD/src/Dio_Ipw.o \
./RTD/src/Dma_Ip.o \
./RTD/src/Dma_Ip_Driver_State.o \
./RTD/src/Dma_Ip_Hw_Access.o \
./RTD/src/Dma_Ip_Irq.o \
./RTD/src/Dma_Ip_Multicore.o \
./RTD/src/Dspi_Ip.o \
./RTD/src/Dspi_Ip_Irq.o \
./RTD/src/Emios_Gpt_Ip.o \
./RTD/src/Emios_Icu_Ip.o \
./RTD/src/Emios_Icu_Ip_Irq.o \
./RTD/src/Flexio_I2c_Ip.o \
./RTD/src/Flexio_Spi_Ip.o \
./RTD/src/Flexio_Spi_Ip_Irq.o \
./RTD/src/Gpt.o \
./RTD/src/Gpt_Ipw.o \
./RTD/src/I2c_Ipw.o \
./RTD/src/Icu.o \
./RTD/src/Icu_Ipw.o \
./RTD/src/Igf_Port_Ip.o \
./RTD/src/IntCtrl_Ip.o \
./RTD/src/Lpi2c_Ip.o \
./RTD/src/Lpi2c_Ip_HwAccess.o \
./RTD/src/Lpi2c_Ip_Irq.o \
./RTD/src/Lpspi_Ip.o \
./RTD/src/Lpspi_Ip_Irq.o \
./RTD/src/Lpuart_Uart_Ip.o \
./RTD/src/Lpuart_Uart_Ip_Irq.o \
./RTD/src/Mcu.o \
./RTD/src/Mcu_Dem_Wrapper.o \
./RTD/src/Mcu_Ipw.o \
./RTD/src/Mpu_M7_Ip.o \
./RTD/src/OsIf_Interrupts.o \
./RTD/src/OsIf_Timer.o \
./RTD/src/OsIf_Timer_System.o \
./RTD/src/OsIf_Timer_System_Internal_Systick.o \
./RTD/src/Pit_Ip.o \
./RTD/src/Platform.o \
./RTD/src/Platform_Ipw.o \
./RTD/src/Port.o \
./RTD/src/Port_Ipw.o \
./RTD/src/Power_Ip.o \
./RTD/src/Power_Ip_AEC.o \
./RTD/src/Power_Ip_CortexM7.o \
./RTD/src/Power_Ip_DCM_GPR.o \
./RTD/src/Power_Ip_FLASH.o \
./RTD/src/Power_Ip_MC_ME.o \
./RTD/src/Power_Ip_MC_RGM.o \
./RTD/src/Power_Ip_MC_RGM_Irq.o \
./RTD/src/Power_Ip_PMC.o \
./RTD/src/Power_Ip_PMC_Irq.o \
./RTD/src/Power_Ip_Private.o \
./RTD/src/Ram_Ip.o \
./RTD/src/Rtc_Ip.o \
./RTD/src/SchM_Adc.o \
./RTD/src/SchM_Dio.o \
./RTD/src/SchM_Gpt.o \
./RTD/src/SchM_I2c.o \
./RTD/src/SchM_Icu.o \
./RTD/src/SchM_Mcl.o \
./RTD/src/SchM_Mcu.o \
./RTD/src/SchM_Platform.o \
./RTD/src/SchM_Port.o \
./RTD/src/SchM_Sbc_fs23.o \
./RTD/src/SchM_Spi.o \
./RTD/src/SchM_Uart.o \
./RTD/src/Siul2_Dio_Ip.o \
./RTD/src/Siul2_Icu_Ip.o \
./RTD/src/Siul2_Icu_Ip_Irq.o \
./RTD/src/Siul2_Port_Ip.o \
./RTD/src/Spi.o \
./RTD/src/Spi_Ipw.o \
./RTD/src/Stm_Ip.o \
./RTD/src/System_Ip.o \
./RTD/src/Tspc_Port_Ip.o \
./RTD/src/Wkpu_Ip.o \
./RTD/src/Wkpu_Ip_Irq.o \
./RTD/src/sbc_fs23_i2c_external_access.o \
./RTD/src/sbc_fs23_spi_external_access.o 

C_DEPS += \
./RTD/src/Adc_Sar_Ip.d \
./RTD/src/Adc_Sar_Ip_Irq.d \
./RTD/src/CDD_I2c.d \
./RTD/src/CDD_Sbc_fs23.d \
./RTD/src/Clock_Ip.d \
./RTD/src/Clock_Ip_Data.d \
./RTD/src/Clock_Ip_Divider.d \
./RTD/src/Clock_Ip_DividerTrigger.d \
./RTD/src/Clock_Ip_ExtOsc.d \
./RTD/src/Clock_Ip_FracDiv.d \
./RTD/src/Clock_Ip_Frequency.d \
./RTD/src/Clock_Ip_Gate.d \
./RTD/src/Clock_Ip_IntOsc.d \
./RTD/src/Clock_Ip_Irq.d \
./RTD/src/Clock_Ip_Monitor.d \
./RTD/src/Clock_Ip_Pll.d \
./RTD/src/Clock_Ip_ProgFreqSwitch.d \
./RTD/src/Clock_Ip_Selector.d \
./RTD/src/Clock_Ip_Specific.d \
./RTD/src/Cmp_Ip.d \
./RTD/src/Dem.d \
./RTD/src/Dem_stub.d \
./RTD/src/Det.d \
./RTD/src/Det_stub.d \
./RTD/src/Dio.d \
./RTD/src/Dio_Ipw.d \
./RTD/src/Dma_Ip.d \
./RTD/src/Dma_Ip_Driver_State.d \
./RTD/src/Dma_Ip_Hw_Access.d \
./RTD/src/Dma_Ip_Irq.d \
./RTD/src/Dma_Ip_Multicore.d \
./RTD/src/Dspi_Ip.d \
./RTD/src/Dspi_Ip_Irq.d \
./RTD/src/Emios_Gpt_Ip.d \
./RTD/src/Emios_Icu_Ip.d \
./RTD/src/Emios_Icu_Ip_Irq.d \
./RTD/src/Flexio_I2c_Ip.d \
./RTD/src/Flexio_Spi_Ip.d \
./RTD/src/Flexio_Spi_Ip_Irq.d \
./RTD/src/Gpt.d \
./RTD/src/Gpt_Ipw.d \
./RTD/src/I2c_Ipw.d \
./RTD/src/Icu.d \
./RTD/src/Icu_Ipw.d \
./RTD/src/Igf_Port_Ip.d \
./RTD/src/IntCtrl_Ip.d \
./RTD/src/Lpi2c_Ip.d \
./RTD/src/Lpi2c_Ip_HwAccess.d \
./RTD/src/Lpi2c_Ip_Irq.d \
./RTD/src/Lpspi_Ip.d \
./RTD/src/Lpspi_Ip_Irq.d \
./RTD/src/Lpuart_Uart_Ip.d \
./RTD/src/Lpuart_Uart_Ip_Irq.d \
./RTD/src/Mcu.d \
./RTD/src/Mcu_Dem_Wrapper.d \
./RTD/src/Mcu_Ipw.d \
./RTD/src/Mpu_M7_Ip.d \
./RTD/src/OsIf_Interrupts.d \
./RTD/src/OsIf_Timer.d \
./RTD/src/OsIf_Timer_System.d \
./RTD/src/OsIf_Timer_System_Internal_Systick.d \
./RTD/src/Pit_Ip.d \
./RTD/src/Platform.d \
./RTD/src/Platform_Ipw.d \
./RTD/src/Port.d \
./RTD/src/Port_Ipw.d \
./RTD/src/Power_Ip.d \
./RTD/src/Power_Ip_AEC.d \
./RTD/src/Power_Ip_CortexM7.d \
./RTD/src/Power_Ip_DCM_GPR.d \
./RTD/src/Power_Ip_FLASH.d \
./RTD/src/Power_Ip_MC_ME.d \
./RTD/src/Power_Ip_MC_RGM.d \
./RTD/src/Power_Ip_MC_RGM_Irq.d \
./RTD/src/Power_Ip_PMC.d \
./RTD/src/Power_Ip_PMC_Irq.d \
./RTD/src/Power_Ip_Private.d \
./RTD/src/Ram_Ip.d \
./RTD/src/Rtc_Ip.d \
./RTD/src/SchM_Adc.d \
./RTD/src/SchM_Dio.d \
./RTD/src/SchM_Gpt.d \
./RTD/src/SchM_I2c.d \
./RTD/src/SchM_Icu.d \
./RTD/src/SchM_Mcl.d \
./RTD/src/SchM_Mcu.d \
./RTD/src/SchM_Platform.d \
./RTD/src/SchM_Port.d \
./RTD/src/SchM_Sbc_fs23.d \
./RTD/src/SchM_Spi.d \
./RTD/src/SchM_Uart.d \
./RTD/src/Siul2_Dio_Ip.d \
./RTD/src/Siul2_Icu_Ip.d \
./RTD/src/Siul2_Icu_Ip_Irq.d \
./RTD/src/Siul2_Port_Ip.d \
./RTD/src/Spi.d \
./RTD/src/Spi_Ipw.d \
./RTD/src/Stm_Ip.d \
./RTD/src/System_Ip.d \
./RTD/src/Tspc_Port_Ip.d \
./RTD/src/Wkpu_Ip.d \
./RTD/src/Wkpu_Ip_Irq.d \
./RTD/src/sbc_fs23_i2c_external_access.d \
./RTD/src/sbc_fs23_spi_external_access.d 


# Each subdirectory must supply rules for building sources it contributes
RTD/src/%.o: ../RTD/src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Standard S32DS C Compiler'
	arm-none-eabi-gcc "@RTD/src/Adc_Sar_Ip.args" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


