MEMORY {
  FLASH (rx)  : ORIGIN = 0x08000000, LENGTH = 512K
  RAM   (rwx) : ORIGIN = 0x20000000, LENGTH = 64K
}
_stack_top = ORIGIN(RAM) + LENGTH(RAM);
SECTIONS {
  .isr_vector : { KEEP(*(.isr_vector)) } > FLASH
  .text : { *(.text*) *(.rodata*) } > FLASH
  _sidata = LOADADDR(.data);
  .data : AT(ADDR(.text) + SIZEOF(.text)) {
    _sdata = .; *(.data*) _edata = .;
  } > RAM
  .bss : { _sbss = .; *(.bss*) *(COMMON) _ebss = .; } > RAM
}
